name: Weekly plan (parent issue)
description: Parent issue for weekly planning + links to area sub-issues
title: "[Weekly] <YYYY-Www> — Weekly objectives"
labels: ["type:planning"]
body:
  - type: textarea
    id: outcomes
    attributes:
      label: Outcomes (must be done by end of week)
      placeholder: |
        1) ...
        2) ...
        3) ...
    validations:
      required: true

  - type: textarea
    id: focus
    attributes:
      label: Focus by area (short)
      placeholder: |
        - Math: ...
        - Deep Learning: ...
        - DSA: ...
        - Writing: ...
    validations:
      required: true

  - type: textarea
    id: subissues
    attributes:
      label: Sub-issues (create + link)
      description: Create one issue per area and paste links here.
      placeholder: |
        - [ ] Math: #123
        - [ ] Deep Learning: #124
        - [ ] DSA: #125
        - [ ] Writing: #126
    validations:
      required: false

  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done (DoD)
      options:
        - label: Sub-issues created and added to the Project with Iteration=@current
          required: true
        - label: Short weekly review note (what worked / didn't / next)
          required: false
